Name:           ros-lunar-camera-info-manager-py
Version:        0.2.3
Release:        0%{?dist}
Summary:        ROS camera_info_manager_py package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/camera_info_manager_py
Source0:        %{name}-%{version}.tar.gz

Requires:       PyYAML
Requires:       python-rospkg
Requires:       ros-lunar-rospy
Requires:       ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-rospy
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-rosunit
BuildRequires:  ros-lunar-sensor-msgs

%description
Python interface for camera calibration information. This ROS package provides a
CameraInfo interface for Python camera drivers similar to the C++
camera_info_manager package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Tue Apr 18 2017 Jack O'Quin <jack.oquin@gmail.com> - 0.2.3-0
- Autogenerated by Bloom

